### ISSUE TITLE
Errors from Pydantic 1.8

### ISSUE THREAD

**Issue by brockfanning** [khaeru/sdmx#63]
I haven't dug into this yet, but I thought I would post this while it's fresh in my mind. I tried upgrading to the latest code, and I get an error just from an "import sdmx" statement, without initializing anything. Here is a trace:

```
Traceback (most recent call last):
  File "foo.py", line 1, in <module>
    import sdmx
  File "/home/brockfanning/repos/sdg-data-rwanda/venv/lib/python3.8/site-packages/sdmx/__init__.py", line 5, in <module>
    from sdmx.client import Client, Request, read_url
  File "/home/brockfanning/repos/sdg-data-rwanda/venv/lib/python3.8/site-packages/sdmx/client.py", line 8, in <module>
    from sdmx.message import Message
  File "/home/brockfanning/repos/sdg-data-rwanda/venv/lib/python3.8/site-packages/sdmx/message.py", line 15, in <module>
    from sdmx import model
  File "/home/brockfanning/repos/sdg-data-rwanda/venv/lib/python3.8/site-packages/sdmx/model.py", line 188, in <module>
    class Annotation(BaseModel):
  File "pydantic/main.py", line 287, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 384, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 369, in pydantic.fields.ModelField._get_field_info
  File "pydantic/fields.py", line 157, in pydantic.fields.FieldInfo._validate
  File "/home/brockfanning/repos/sdg-data-rwanda/venv/lib/python3.8/site-packages/sdmx/model.py", line 166, in __eq__
    return self.localizations == other.localizations
AttributeError: 'UndefinedType' object has no attribute 'localizations'
```

Where "foo.py" is this:

```
import sdmx

print('Hello world')
```

**Comment by brockfanning** [comment]
Actually this seems to happen no matter what version I use - so maybe there is a problem in some other project. I'm still investigating.

**Comment by brockfanning** [comment]
Ah ok, I think the problem is coming from the pydantic library, which released a new version yesterday. If I pin to the previous version of pydantic, it works fine:

```
sdmx1==2.2.0
pydantic==1.7.3
```

**Comment by khaeru** [comment]
I merged #62 and released v2.2.1 to address this. Have you tried with that version?

I also filed samuelcolvin/pydantic#2422, which the maintainers there have already fixed, though no timeline on when they'll release ≥ 1.8.1 containing the fix. When it's in, I'll check and remove the exclusion.

**Comment by brockfanning** [comment]
@khaeru Cool - has 2.2.1 been uploaded to the package manager? I can't seem to access with `sdmx1==2.2.1`. Should I just pin to its tag in Github for now?

**Comment by khaeru** [comment]
Sorry—I'd pushed the RC tag, but not the final one. It's on PyPI now—https://pypi.org/project/sdmx1/#history —please try again.

**Comment by brockfanning** [comment]
Great, that fixed it, thank you!
